# Generated by Django 4.2.2 on 2023-06-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='hgchfh', max_length=150),
            preserve_default=False,
        ),
    ]
